async function testExports() {
  const baseUrl = 'http://localhost:3000';
  
  // Login
  const loginRes = await fetch(`${baseUrl}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'demo@apexapparel.com', password: 'Password123!' }),
  });
  const setCookie = loginRes.headers.get('set-cookie');
  const match = setCookie?.match(/three_pl_auditor_session=[^;]+/);
  const cookie = match ? match[0] : '';
  const headers = { Cookie: cookie };

  console.log('Fetching audits...');
  const auditsRes = await fetch(`${baseUrl}/api/audits`, { headers });
  const data = await auditsRes.json();
  const invoice = data.invoices[0];
  console.log('Auditing invoice:', invoice.id, invoice.invoiceNumber);

  console.log('Testing CSV export...');
  const csvRes = await fetch(`${baseUrl}/api/audits/${invoice.id}/export-csv`, { headers });
  console.log('CSV Status:', csvRes.status, 'Content-Type:', csvRes.headers.get('content-type'));
  if (!csvRes.ok) {
    const text = await csvRes.text();
    console.error('CSV Error Body:', text.slice(0, 300));
  } else {
    const csvText = await csvRes.text();
    console.log('CSV Content Lines:', csvText.split('\n').length);
    console.log('First 2 lines:', csvText.split('\n').slice(0, 2));
  }

  console.log('\nTesting PDF export...');
  const pdfRes = await fetch(`${baseUrl}/api/audits/${invoice.id}/export-pdf`, { headers });
  console.log('PDF Status:', pdfRes.status, 'Content-Type:', pdfRes.headers.get('content-type'));
  if (!pdfRes.ok) {
    const text = await pdfRes.text();
    console.error('PDF Error Body:', text.slice(0, 300));
  } else {
    const buffer = await pdfRes.arrayBuffer();
    console.log('PDF Generated Bytes:', buffer.byteLength);
  }
}

testExports().catch(console.error);
